baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Edasaki Blog'

[params]
 description = "The fastest blog"
 dateFormat = "Jan 2, 2006"

[taxonomies]
 category = "categories"
 author = "authors"